trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.7.5'
  displayName: 'Install Terraform'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/environments/dev'
    backendServiceArm: 'Azure-OIDC' # Replace with your service connection name
    backendAzureRmResourceGroupName: '<your-tfstate-resource-group-name>'
    backendAzureRmStorageAccountName: '<your-tfstate-storage-account-name>'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/environments/dev'
    environmentServiceNameAzureRM: 'Azure-OIDC' # Replace with your service connection name