
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.7.5'
  displayName: 'Install Terraform'

- task: AzureCLI@2
  inputs:
    azureSubscription: '<your-service-connection-name>' # Replace with your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
  displayName: 'Azure Login'
  env:
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
    AZURE_TENANT_ID: $(AZURE_TENANT_ID)

- script: |
    terraform init -input=false
    terraform plan -input=false -no-color
  workingDirectory: 'infra/environments/dev'
  displayName: 'Terraform Init/Plan (dev)'
